Administration/Controllers/ReturnRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Nop.Admin.Models.Orders;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Orders;
using Nop.Services;
using Nop.Services.Customers;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;

namespace Nop.Admin.Controllers
{
    public partial class ReturnRequestController : BaseAdminController
    {
        #region Fields

        private readonly IReturnRequestService _returnRequestService;
        private readonly IOrderService _orderService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPermissionService _permissionService;
        private readonly IDownloadService _downloadService;

        #endregion Fields

        #region Constructors

        public ReturnRequestController(IReturnRequestService returnRequestService,
            IOrderService orderService,
            ICustomerService customerService,
            IDateTimeHelper dateTimeHelper,
            ILocalizationService localizationService,
            IWorkContext workContext,
            IWorkflowMessageService workflowMessageService,
            ICustomerActivityService customerActivityService, 
            IPermissionService permissionService,
            IDownloadService downloadService)
        {
            this._returnRequestService = returnRequestService;
            this._orderService = orderService;
            this._customerService = customerService;
            this._dateTimeHelper = dateTimeHelper;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._workflowMessageService = workflowMessageService;
            this._customerActivityService = customerActivityService;
            this._permissionService = permissionService;
            this._downloadService = downloadService;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected virtual void PrepareReturnRequestModel(ReturnRequestModel model,
            ReturnRequest returnRequest, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            if (returnRequest == null)
                throw new ArgumentNullException("returnRequest");

            var orderItem = _orderService.GetOrderItemById(returnRequest.OrderItemId);
            if (orderItem != null)
            {
                model.ProductId = orderItem.ProductId;
                model.ProductName = orderItem.Product.Name;
                model.OrderId = orderItem.OrderId;
                model.AttributeInfo = orderItem.AttributeDescription;
                model.CustomOrderNumber = orderItem.Order.CustomOrderNumber;
            }
            model.Id = returnRequest.Id;
            model.CustomNumber = returnRequest.CustomNumber;
            model.CustomerId = returnRequest.CustomerId;
            var customer = returnRequest.Customer;
            model.CustomerInfo = customer.IsRegistered() ? customer.Email : _localizationService.GetResource("Admin.Customers.Guest");
            model.Quantity = returnRequest.Quantity;
            model.ReturnRequestStatusStr = returnRequest.ReturnRequestStatus.GetLocalizedEnum(_localizationService, _workContext);

            var download = _downloadService.GetDownloadById(returnRequest.UploadedFileId);
            model.UploadedFileGuid = download != null ? download.DownloadGuid : Guid.Empty;
            model.CreatedOn = _dateTimeHelper.ConvertToUserTime(returnRequest.CreatedOnUtc, DateTimeKind.Utc);
            if (!excludeProperties)
            {
                model.ReasonForReturn = returnRequest.ReasonForReturn;
                model.RequestedAction = returnRequest.RequestedAction;
                model.CustomerComments = returnRequest.CustomerComments;
                model.StaffNotes = returnRequest.StaffNotes;
                model.ReturnRequestStatusId = returnRequest.ReturnRequestStatusId;
            }
        }

        #endregion

        #region Methods

        //list
        public virtual ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var model = new ReturnRequestListModel
            {
                ReturnRequestStatusList = ReturnRequestStatus.Cancelled.ToSelectList(false).ToList(),
                ReturnRequestStatusId = -1
            };

            model.ReturnRequestStatusList.Insert(0, new SelectListItem
            {
                Value = "-1",
                Text = _localizationService.GetResource("Admin.ReturnRequests.SearchReturnRequestStatus.All"),
                Selected = true
            });

            return View(model);
        }

        [HttpPost]
        public virtual ActionResult List(DataSourceRequest command, ReturnRequestListModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedKendoGridJson();

            var rrs = model.ReturnRequestStatusId == -1 ? null : (ReturnRequestStatus?) model.ReturnRequestStatusId;
            
            var startDateValue = model.StartDate == null ? null
                            : (DateTime?)_dateTimeHelper.ConvertToUtcTime(model.StartDate.Value, _dateTimeHelper.CurrentTimeZone);

            var endDateValue = model.EndDate == null ? null
                            : (DateTime?)_dateTimeHelper.ConvertToUtcTime(model.EndDate.Value, _dateTimeHelper.CurrentTimeZone).AddDays(1);

            var returnRequests = _returnRequestService.SearchReturnRequests(0, 0, 0, model.CustomNumber, rrs, startDateValue, endDateValue, command.Page - 1, command.PageSize);
            var returnRequestModels = new List<ReturnRequestModel>();
            foreach (var rr in returnRequests)
            {
                var m = new ReturnRequestModel();
                PrepareReturnRequestModel(m, rr, false);
                returnRequestModels.Add(m);
            }
            var gridModel = new DataSourceResult
            {
                Data = returnRequestModels,
                Total = returnRequests.TotalCount,
            };

            return Json(gridModel);
        }

        //edit
        public virtual ActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var returnRequest = _returnRequestService.GetReturnRequestById(id);
            if (returnRequest == null)
                //No return request found with the specified id
                return RedirectToAction("List");
            
            var model = new ReturnRequestModel();
            PrepareReturnRequestModel(model, returnRequest, false);
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual ActionResult Edit(ReturnRequestModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var returnRequest = _returnRequestService.GetReturnRequestById(model.Id);
            if (returnRequest == null)
                //No return request found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                returnRequest.Quantity = model.Quantity;
                returnRequest.ReasonForReturn = model.ReasonForReturn;
                returnRequest.RequestedAction = model.RequestedAction;
                returnRequest.CustomerComments = model.CustomerComments;
                returnRequest.StaffNotes = model.StaffNotes;
                returnRequest.ReturnRequestStatusId = model.ReturnRequestStatusId;
                returnRequest.UpdatedOnUtc = DateTime.UtcNow;
                _customerService.UpdateCustomer(returnRequest.Customer);

                //activity log
                _customerActivityService.InsertActivity("EditReturnRequest", _localizationService.GetResource("ActivityLog.EditReturnRequest"), returnRequest.Id);

                SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Updated"));
                return continueEditing ? RedirectToAction("Edit", new { id = returnRequest.Id}) : RedirectToAction("List");
            }


            //If we got this far, something failed, redisplay form
            PrepareReturnRequestModel(model, returnRequest, true);
            return View(model);
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("notify-customer")]
        public virtual ActionResult NotifyCustomer(ReturnRequestModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var returnRequest = _returnRequestService.GetReturnRequestById(model.Id);
            if (returnRequest == null)
                //No return request found with the specified id

Administration/Views/ReturnRequest/Edit.cshtml
@model ReturnRequestModel

@{
    //page title
    ViewBag.Title = T("Admin.ReturnRequests.EditReturnRequestDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Return requests");
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ReturnRequests.EditReturnRequestDetails") 
            <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.ReturnRequests.BackToList").Text, "List")</small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="notify-customer" class="btn bg-aqua">
                <i class="fa fa-envelope-o"></i>
                @T("Admin.ReturnRequests.NotifyCustomer")
            </button>
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequest-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
@Html.DeleteConfirmation("returnrequest-delete")

Administration/Views/ReturnRequest/List.cshtml
@model ReturnRequestListModel

@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.ReturnRequests").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Return requests");
}

@Html.AntiForgeryToken()
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.ReturnRequests")
    </h1>
    <div class="pull-right">
        &nbsp;
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">

            <div class="panel panel-default panel-search">
                <div class="panel-body">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.NopLabelFor(model => model.CustomNumber)
                                </div>
                                <div class="col-md-8">
                                    @Html.NopEditorFor(model => model.CustomNumber)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.NopLabelFor(model => model.StartDate)
                                </div>
                                <div class="col-md-8">
                                    @Html.NopEditorFor(model => model.StartDate)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.NopLabelFor(model => model.EndDate)
                                </div>
                                <div class="col-md-8">
                                    @Html.NopEditorFor(model => model.EndDate)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.NopLabelFor(model => model.ReturnRequestStatusId)
                                </div>
                                <div class="col-md-8">
                                    @Html.NopDropDownListFor(model => model.ReturnRequestStatusId, Model.ReturnRequestStatusList)
                                </div>
                            </div>

                            <div class="col-md-8 col-md-offset-4">
                                <button type="button" id="search-returnrequests" class="btn btn-primary btn-search">
                                    <i class="fa fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <p>
                        @T("Admin.ReturnRequests.Description")
                    </p>
                    <div id="returnrequests-grid"></div>

                    <script>
                        $(document)
                            .ready(function() {
                                $("#returnrequests-grid")
                                    .kendoGrid({
                                        dataSource: {
                                            type: "json",
                                            transport: {
                                                read: {
                                                    url: "@Html.Raw(Url.Action("List", "ReturnRequest"))",
                                                    type: "POST",
                                                    dataType: "json",
                                                    data: additionalData
                                                }
                                            },
                                            schema: {
                                                data: "Data",
                                                total: "Total",
                                                errors: "Errors"
                                            },
                                            error: function(e) {
                                                display_kendoui_grid_error(e);
                                                // Cancel the changes
                                                this.cancelChanges();
                                            },
                                            pageSize: @(defaultGridPageSize),
                                            serverPaging: true,
                                            serverFiltering: true,
                                            serverSorting: true
                                        },
                                        pageable: {
                                            refresh: true,
                                            pageSizes: [@(gridPageSizes)],
                                            @Html.Partial("_GridPagerMessages")
                                        },
                                        editable: {
                                            confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                            mode: "inline"
                                        },
                                        scrollable: false,
                                        columns: [
                                            {
                                                field: "CustomNumber",
                                                title: "@T("Admin.ReturnRequests.Fields.CustomNumber")",
                                                width: 100
                                            }, {
                                                field: "ProductName",
                                                title: "@T("Admin.ReturnRequests.Fields.Product")",
                                                width: 350,
                                                template:
                                                    '# if(ProductId > 0) {# <a href="@Url.Content("~/Admin/Product/Edit/")#=ProductId#">#:ProductName#</a> ' +
                                                        '# if(AttributeInfo && AttributeInfo.length > 0) {# <div>#=AttributeInfo#</div> #} # #} else {# order item is deleted #} #'
                                            }, {
                                                field: "Quantity",
                                                title: "@T("Admin.ReturnRequests.Fields.Quantity")",
                                                width: 100
                                            }, {
                                                field: "CustomerId",
                                                title: "@T("Admin.ReturnRequests.Fields.Customer")",
                                                width: 200,
                                                template:
                                                    '<a href="@Url.Content("~/Admin/Customer/Edit/")#=CustomerId#">#:CustomerInfo#</a>'
                                            }, {
                                                field: "CustomOrderNumber",
                                                title: "@T("Admin.ReturnRequests.Fields.CustomOrderNumber")",
                                                width: 200,
                                                headerAttributes: { style: "text-align:center" },
                                                attributes: { style: "text-align:center" },
                                                template: '# if(OrderId > 0) {# <a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")#=OrderId#"><i class="fa fa-eye"></i>#=CustomOrderNumber# - @T("Admin.Common.View")</a> #} else {# order item is deleted #} #'
                                            }, {
                                                field: "ReturnRequestStatusStr",
                                                title: "@T("Admin.ReturnRequests.Fields.Status")",
                                                width: 100
                                            }, {
                                                field: "CreatedOn",
                                                title: "@T("Admin.ReturnRequests.Fields.CreatedOn")",
                                                width: 100,
                                                type: "date",
                                                format: "{0:G}"
                                            }, {
                                                field: "Id",
                                                title: "@T("Admin.Common.Edit")",
                                                width: 100,
                                                headerAttributes: { style: "text-align:center" },
                                                attributes: { style: "text-align:center" },
                                                template: '<a class="btn btn-default" href="Edit/#=Id#"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</a>'
                                            }
                                        ]
                                    });
                            });
                    </script>

                    <script type="text/javascript">
                        $(document)
                        .ready(function() {
                            $('#search-returnrequests')
                                .click(function() {
                                    var grid = $('#returnrequests-grid').data('kendoGrid');
                                    grid.dataSource.page(1); //new search. Set page size to 1
                                    //grid.dataSource.read(); we already loaded the grid above using "page" function
                                    return false;
                                });
                        });

                        function additionalData() {
                            var data = {
                                StartDate: $('#@Html.FieldIdFor(model => model.StartDate)').val(),
                                EndDate: $('#@Html.FieldIdFor(model => model.EndDate)').val(),
                                CustomNumber: $('#@Html.FieldIdFor(model => model.CustomNumber)').val(),
                                ReturnRequestStatusId: $('#@Html.FieldIdFor(model => model.ReturnRequestStatusId)')
                                    .val()
                            };
                            addAntiForgeryToken(data);
                            return data;
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

Administration/Views/ReturnRequest/_CreateOrUpdate.cshtml
@model ReturnRequestModel

@using Nop.Core.Domain.Orders;
@using Nop.Services

@Html.ValidationSummary(false)
@Html.HiddenFor(model => model.Id)

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.CustomNumber)
                        </div>
                        <div class="col-md-9">
                            @Html.NopDisplayFor(model => model.CustomNumber)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.CustomOrderNumber)
                        </div>
                        <div class="col-md-9">
                            @if (Model.OrderId > 0)
                            {
                                @Html.ActionLink(Model.CustomOrderNumber, "Edit", "Order", new {id = Model.OrderId}, new {})
                            }
                            else
                            {
                                <text>Order item is deleted</text>
                            }
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.CustomerId)
                        </div>
                        <div class="col-md-9">
                            @Html.ActionLink(Model.CustomerInfo, "Edit", "Customer", new { id = Model.CustomerId }, new { })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.ProductName)
                        </div>
                        <div class="col-md-9">
                            @if (Model.ProductId > 0)
                            {
                                @Html.ActionLink(Model.ProductName, "Edit", "Product", new { id = Model.ProductId }, new { })
                            }
                            else
                            {
                                <text>Order item is deleted</text>
                            }
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.Quantity)
                        </div>
                        <div class="col-md-9">
                            @Html.NopEditorFor(model => model.Quantity)
                            @Html.ValidationMessageFor(model => model.Quantity)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.ReturnRequestStatusId)
                        </div>
                        <div class="col-md-9">
                            @Html.NopDropDownListFor(model => model.ReturnRequestStatusId, ((ReturnRequestStatus)Model.ReturnRequestStatusId).ToSelectList())
                            @Html.ValidationMessageFor(model => model.ReturnRequestStatusId)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.ReasonForReturn)
                        </div>
                        <div class="col-md-9">
                            @Html.NopEditorFor(model => model.ReasonForReturn, required: true)
                            @Html.ValidationMessageFor(model => model.ReasonForReturn)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.RequestedAction)
                        </div>
                        <div class="col-md-9">
                            @Html.NopEditorFor(model => model.RequestedAction, required: true)
                            @Html.ValidationMessageFor(model => model.RequestedAction)
                        </div>
                    </div>
                    @if (Model.UploadedFileGuid != Guid.Empty)
                    {
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.NopLabelFor(model => model.UploadedFileGuid)
                            </div>
                            <div class="col-md-9">
                                <a href="@Url.Action("DownloadFile", "Download", new {downloadGuid = Model.UploadedFileGuid})">@T("Admin.ReturnRequests.Fields.UploadedFile.Download")</a>
                            </div>
                        </div>
                    }
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.CustomerComments)
                        </div>
                        <div class="col-md-9">
                            @Html.NopTextAreaFor(model => model.CustomerComments)
                            @Html.ValidationMessageFor(model => model.CustomerComments)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.StaffNotes)
                        </div>
                        <div class="col-md-9">
                            @Html.NopTextAreaFor(model => model.StaffNotes)
                            @Html.ValidationMessageFor(model => model.StaffNotes)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.NopLabelFor(model => model.CreatedOn)
                        </div>
                        <div class="col-md-9">
                            @Html.NopDisplayFor(model => model.CreatedOn)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>